### ISSUE TITLE
Fails to build with ffmpeg 3.0

### ISSUE THREAD

**Issue by yurivict** [jart/hiptext#36]
```
  movie.cc:56:42: error: use of undeclared identifier 'PIX_FMT_RGB24'; did you mean
	'AV_PIX_FMT_RGB24'?
			  width_, height_, PIX_FMT_RGB24, SWS_FAST_BILINEAR,
					   ^~~~~~~~~~~~~
					   AV_PIX_FMT_RGB24
  movie.cc:64:18: error: use of undeclared identifier 'avcodec_alloc_frame'
    CHECK(frame_ = avcodec_alloc_frame());
		   ^
```

Possible fix: s/PIX_FMT/AV_&/ + s/avcodec_alloc_frame/av_frame_alloc/

**Comment by jart** [comment]
This is fixed in https://github.com/jart/hiptext/pull/27 but the problem is the PR needs to be modified to maintain compatibility with Ubuntu 14.04. So hopefully @tombh will be kind enough to add the necessary define statements so we can get that merged.

**Comment by WindProphet** [comment]
this problem also occurs in ffmpeg 4.0+
I write the issue 
https://github.com/jart/hiptext/issues/53 and pull requests https://github.com/jart/hiptext/pull/52
